### ISSUE TITLE
Mari-OCR-takeover of liv letters in generated symbols list

### ISSUE THREAD

**Issue by rueter** [giellalt/lang-liv#1]
Two symbols, causing problems in mhr OCR <ʼ> (U+02BC) and <Ȭ> (U+022C), are actually parts of the lang-liv description.
On the one hand, <ʼ> (U+02BC) is used in the pedagogic description of the language and filtered out of the normative analyzers and generators. Despite this the fact that <ʼ> (U+02BC) MODIFIER LETTER APOSTROPHE is declared in lang-liv/src/fst/generated_files/symbols.lexc means that ZERO is considered by the tokenizer to be a possible surface realization of it in places where it should not be, i.e. between words.

```
echo 'Ta īend väzzõnõks. Tund ȭdõg. '  |perl -wpne 's/(\<)/\[$1/g; s/(\>)/$1\]/g;'| hfst-tokenise -S -g --giella-cg -W $GIELLA_HOME/lang-liv/tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 -g $GIELLA_HOME/lang-liv/src/cg3/disambiguator.cg3|less
```
produces:

```
...
: 
"<väzzõnõks>"
        "väzzõ" V IV Act PrfPrc Sg Ins @X
"<.>"
        "." CLB

"<>"
        "<>" "ʼ" N Symbol @X
: 
"<Tund>"
        "tundõ" V TV Imprt Sg2 @X
        "tundõ" V TV Ind ConNeg Sg @X
: 
"<ȭdõg>"
        "ȭdõg" N Sg Nom @<SUBJ
"<.>"
        "." CLB

"<>"
        "<>" "ʼ" N Symbol @HNOUN
: 
"<>"
        "<>" "ʼ" N Symbol @HNOUN
:\n
"<>"
        "<>" "ʼ" N Symbol @HNOUN

``` 
The second "symbol" a real letter, <Ȭ> (U+022C) LATIN CAPITAL LETTER O WITH TILDE AND MACRON
causes words not to be recognized by the tokenizer:
```
echo 'Ȭdõgižis mēg sīem kaffe, lȭinagizt pierāst ma vȯstīz vȯzzõ.'  |perl -wpne 's/(\<)/\[$1/g; s/(\>)/$1\]/g;'| hfst-tokenise -S -g --giella-cg -W $GIELLA_HOME/lang-liv/tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 -g $GIELLA_HOME/lang-liv/src/cg3/disambiguator.cg3|less
```
begins simply as:
```
"<Ȭdõgižis>"
        "Ȭdõgižis" ?
: 
"<mēg>"
        "mēg" Pron Pers Pl1 Nom @X
: 
"<sīem>"
        "sīedõ" V TV Ind Prs Pl1 @+FMAINV
: 
"<kaffe>"
        "kaffe" N Sg Nom @X
        "kaffe" N Sg Par @X

```

Both problems can be dealt with locally by simply commenting them out in the generated symbols list. 

Perhaps, this is not a matter of the symbols file, since the same file also contains the lut letter schwa <ə> (U+0259) and a couple others, but this does not affect the tokenizer in lut.

**Comment by snomos** [comment]
The real issue is that the symbol list has been expanded with letters (ie the Mari OCR list). The symbol list should only contain actual symbols, ie graphemes that are used in isolation in text (in some cases with inflection), and never graphemes that can be part of a word. Example: `$` is a symbol, typically functioning as a noun, whereas `Ȭ` is not.

The correct solution is to move the letters in the list from the symbol file to lang-mhr. @Trondtr can you fix this?

**Comment by snomos** [comment]
From commit https://github.com/giellalt/giella-shared/commit/92e37506425f9c9ba2dd33e0778f094763020534:

> Experimenting with symbols: Adding symbols from mhr OCR, now no more wordforms following : after hfst-tokenize. TODO: check for negative consequences of adding symbols.

Now the negative consequenses have materialised, and they are serious 🙂

**Comment by Trondtr** [comment]
I have now checked in a version of the giella-shared file without the letter symbols, and without the combining characters.

Please check whether the liv analyser  now behaves better.

**Comment by rueter** [comment]
I have updated the `giella-shared`,

```sh
cd lang-liv
make clean
./autogen.sh
./configure --enable-tokenisers --enable-spellers GIELLA_CORE=/Users/rueter/Documents/Github/giellalt/giella-core/dir GIELLA_SHARED=/Users/rueter/Documents/Github/giellalt/giella-shared/dir
make
```
Subsequently no problems with tokenization.

**Comment by snomos** [comment]
Excellent!
